language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - sudo apt-get update > /dev/null

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - php tests/prepare_tokens.php

script:
  - vendor/bin/phpunit --bootstrap tests/bootstrap.php --coverage-clover=coverage.xml -c tests/phpunit.xml tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)